# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - "./volumes/log:/var/log/elk"
    - "./volumes/log:/var/log/elasticsearch"
    - "./volumes/data:/var/data/elk"
    - "./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml"
  environment:
    - MAX_MAP_COUNT=262144
